{{- if .Values.etcd.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "pulsar.fullname" . }}-etcd
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pulsar.labels" . | nindent 4 }}
    app.kubernetes.io/component: etcd
spec:
  serviceName: {{ include "pulsar.fullname" . }}-etcd
  replicas: 1
  selector:
    matchLabels:
      {{- include "pulsar.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: etcd
  template:
    metadata:
      labels:
        {{- include "pulsar.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: etcd
    spec:
      {{- include "pulsar.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: etcd
          image: {{ printf "%s:%s" .Values.etcd.image.repository .Values.etcd.image.tag }}
          imagePullPolicy: {{ .Values.etcd.image.pullPolicy }}
          command:
            - etcd
            - --name=pulsar-node1
            - --data-dir=/etcd-data
            - --listen-client-urls=http://0.0.0.0:2379
            - --advertise-client-urls=http://{{ include "pulsar.fullname" . }}-etcd:2379
            - --listen-peer-urls=http://0.0.0.0:2380
            - --initial-advertise-peer-urls=http://{{ include "pulsar.fullname" . }}-etcd:2380
            - --initial-cluster=pulsar-node1=http://{{ include "pulsar.fullname" . }}-etcd:2380
            - --initial-cluster-token=pulsar
            - --initial-cluster-state=new
          ports:
            - name: client
              containerPort: 2379
              protocol: TCP
            - name: peer
              containerPort: 2380
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - etcdctl
                - --endpoints=http://localhost:2379
                - endpoint
                - health
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            exec:
              command:
                - etcdctl
                - --endpoints=http://localhost:2379
                - endpoint
                - health
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
            - name: etcd-data
              mountPath: /etcd-data
          {{- with .Values.etcd.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
  {{- if .Values.etcd.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: etcd-data
      spec:
        accessModes: [{{ .Values.etcd.persistence.accessMode | quote }}]
        {{- if .Values.etcd.persistence.storageClass }}
        storageClassName: {{ .Values.etcd.persistence.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.etcd.persistence.size }}
  {{- else }}
      volumes:
        - name: etcd-data
          emptyDir: {}
  {{- end }}
{{- end }}
