{{- if not .Values.jwt.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-jwt" (include "pulsar.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pulsar.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.jwt.secret | quote }}
{{- end }}
